# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_original', models.CharField(max_length=512)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('color', models.CharField(db_index=True, max_length=128)),
                ('image_url', models.URLField(max_length=1536)),
                ('date_created', models.DateField(db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_index=True, default=0)),
                ('quantity_reserved', models.IntegerField(db_index=True, default=0)),
                ('date_created', models.DateField(db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paparazzi.Item')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('title', 'color')]),
        ),
    ]
