# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paparazzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItemStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.IntegerField(db_index=True, default=0)),
                ('date_created', models.DateField(db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_reserved',
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(max_length=1536, null=True),
        ),
        migrations.AddField(
            model_name='useritemstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paparazzi.Stock'),
        ),
        migrations.AddField(
            model_name='useritemstock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
