# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paparazzi', '0003_auto_20170630_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=1536, null=True),
        ),
    ]
