# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paparazzi', '0004_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='being_sold',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
