# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paparazzi', '0005_item_being_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_found_sold',
            field=models.DateField(db_index=True, default=None),
        ),
    ]
