# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 21:11
from __future__ import unicode_literals

from django.db import migrations
import paparazzi.models


class Migration(migrations.Migration):

    dependencies = [
        ('paparazzi', '0006_item_date_found_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=paparazzi.models.EnumField(choices=[('bracelet', 'Bracelet'), ('earring', 'Earring'), ('ring', 'Ring'), ('necklace', 'Necklace'), ('hair-clip', 'Hair-Clip'), ('headband', 'Headband')], default=None),
        ),
    ]
