# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import paparazzi.models


class Migration(migrations.Migration):

    dependencies = [
        ('paparazzi', '0007_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=paparazzi.models.EnumField(choices=[('bracelet', 'Bracelet'), ('earring', 'Earring'), ('ring', 'Ring'), ('necklace', 'Necklace'), ('hair-clip', 'Hair-Clip'), ('headband', 'Headband')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_found_sold',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
    ]
